modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
showAsResourcePack=false

[[mods]]
modId="lifeessence"
version="1.0.1"
displayName="生命精油"
authors="liuge"
description="添加可以增加最大生命值的生命精油物品"
logoFile="logo.png"

[[dependencies.lifeessence]]
modId="forge"
mandatory=true
versionRange="[47.4.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.lifeessence]]
modId="deathpenalty"
mandatory=true
versionRange="[1.1.0,)"
ordering="AFTER"
side="BOTH"